"""Calculated holiday baseline providers."""

from __future__ import annotations

from importlib.metadata import version
from typing import TYPE_CHECKING

import holidays

from .models import Description, HolidayRecord, HolidayType

if TYPE_CHECKING:
    from collections.abc import Sequence
    from datetime import date


class PythonHolidaysProvider:
    """Baseline generated by the MIT-licensed python-holidays library."""

    @property
    def version(self) -> str:
        """Return the installed python-holidays version."""
        return version("holidays")

    def holidays_for(
        self,
        country_code: str,
        years: Sequence[int],
    ) -> tuple[HolidayRecord, ...]:
        """Calculate normalized public holidays."""
        english = holidays.country_holidays(
            country_code,
            years=list(years),
            language="en_US",
        )
        korean: dict[date, str] = {}
        if country_code == "KR":
            korean_calendar = holidays.country_holidays(
                country_code,
                years=list(years),
                language="ko",
            )
            korean = dict(korean_calendar.items())
        records = (
            HolidayRecord(
                name=name,
                date=holiday_date,
                type=HolidayType.NATIONAL,
                description=Description(
                    en=name,
                    ko=korean.get(holiday_date, name),
                ),
            )
            for holiday_date, name in english.items()
        )
        return tuple(sorted(records, key=lambda item: (item.date, item.name)))
